version: '3'

services:
    apache:
        container_name: apache
        build: .docker/apache
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .docker/data/logs/apache:/var/log/apache2:delegated
        depends_on:
            - php-fpm
        networks:
            - internal

    php-fpm:
        container_name: php-fpm
        build:
            context: .docker/php-fpm
        volumes:
            - ./:/var/www/html:delegated
            - .docker/data/logs/php:/var/log/php:delegated
        expose:
            - 9000
        networks:
            - internal

    postgress:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: "dashboard"
            POSTGRES_USER: "lateir"
            POSTGRES_PASSWORD: "123"
            PGDATA: "/var/lib/postgresql/data/pgdata"
            volumes: ".:/var/lib/postgresql/data"
            # - "../2. Init Database:/docker-entrypoint-initdb.d"
            
        expose:
            - 5432
        networks:
            - internal

networks:
    internal:
